### ISSUE TITLE
Mesh: AttributeError: kVertexFormatColor

### ISSUE THREAD

**Issue by martinwang2002** [K0lb3/UnityPy#100]
**Code**
On line 1029 on Mesh.py, UnityPy calles the `kVertexFormatColor` of Enum `VertexFormat2017`, which is not defined

https://github.com/K0lb3/UnityPy/blob/691e12b995a1f82f562dedc690b7df691d7d4fa8/UnityPy/classes/Mesh.py#L1029

https://github.com/K0lb3/UnityPy/blob/691e12b995a1f82f562dedc690b7df691d7d4fa8/UnityPy/classes/Mesh.py#L1081-L1093

**Error**
The error message that is produced by python.
```
Traceback (most recent call last):
  File ".venv/lib/python3.10/site-packages/UnityPy/files/ObjectReader.py", line 156, in read
    raise e
  File ".venv/lib/python3.10/site-packages/UnityPy/files/ObjectReader.py", line 154, in read
    obj = getattr(classes, self.type.name, classes.Object)(self)
  File ".venv/lib/python3.10/site-packages/UnityPy/classes/Mesh.py", line 519, in __init__
    self.ReadVertexData()
  File ".venv/lib/python3.10/site-packages/UnityPy/classes/Mesh.py", line 587, in ReadVertexData
    MeshHelper.ToVertexFormat(m_Channel.format, version),
  File ".venv/lib/python3.10/site-packages/UnityPy/classes/Mesh.py", line 1029, in ToVertexFormat
    format == VertexFormat2017.kVertexFormatColor
  File "/usr/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: kVertexFormatColor
```

**Bug**
UnityPy cannot successfully export Mesh files.

**To Reproduce**
- a copy of the file that causes the problem: Feel free to ask me to provide it.
- following data:
  - Python version: 3.10.2
  - UnityPy version: 1.8.4

**Comment by K0lb3** [comment]
Thanks for reporting the problem.
[cab5caf](https://github.com/K0lb3/UnityPy/commit/cab5cafdc99313e8f2c10a2b328a17b92519e8ea) fixes the issue.

**Comment by martinwang2002** [comment]
I think this issue still exists for 1.8.5

Now, the traceback gives 
```
Traceback (most recent call last):
  File ".venv/lib/python3.10/site-packages/UnityPy/classes/Mesh.py", line 479, in __init__
    self.m_VertexData = VertexData(reader)
  File ".venv/lib/python3.10/site-packages/UnityPy/classes/Mesh.py", line 144, in __init__
    self.GetStreams()
  File ".venv/lib/python3.10/site-packages/UnityPy/classes/Mesh.py", line 191, in GetStreams
    stride += m_Channel.dimension * MeshHelper.GetFormatSize(
  File ".venv/lib/python3.10/site-packages/UnityPy/classes/Mesh.py", line 920, in GetFormatSize
    elif format == VertexFormat.kVertexFormatColor:
  File "/usr/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
```

**Comment by martinwang2002** [comment]
https://github.com/Perfare/AssetStudio/blob/3660b4ed673e684aab5a9d71958938334f1c7559/AssetStudio/Classes/Mesh.cs#L1296-L1318

It seems that AssetStudio does not return value for `VertexFormat.kVertexFormatColor` in GetFormatSize function

**Comment by K0lb3** [comment]
Ah, yeah, AssetStudio simplified GetFormatSize a bit.
I did that just now with a new commit.

**Comment by martinwang2002** [comment]
lgtm
