### ISSUE TITLE
How to Specify Unity Version?

### ISSUE THREAD

**Issue by MikuAuahDark** [K0lb3/UnityPy#104]
I have a bundle file that has its Unity version set as `0.0.0` (stripped). Opening it in AssetStudio requires me to specify the version (Perfare/AssetStudio#860). UnityPy gives me an error when trying to extract Texture2D from it.

```
Traceback (most recent call last):
  File "D:\stripped\path\update.py", line 450, in <module>
    extract_bundle(modeldata, destdir)
  File "D:\stripped\path\update.py", line 190, in extract_bundle
    data = obj.read()
  File "C:\Program Files\Python310\lib\site-packages\UnityPy\files\ObjectReader.py", line 156, in read
    raise e
  File "C:\Program Files\Python310\lib\site-packages\UnityPy\files\ObjectReader.py", line 154, in read
    obj = getattr(classes, self.type.name, classes.Object)(self)
  File "C:\Program Files\Python310\lib\site-packages\UnityPy\classes\Texture2D.py", line 128, in __init__
    self.m_TextureFormat = TextureFormat(reader.read_int())
  File "C:\Program Files\Python310\lib\enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "C:\Program Files\Python310\lib\enum.py", line 710, in __new__
    raise ve_exc
ValueError: 1024 is not a valid TextureFormat
```

I know the exact version of the bundle, thus the question is how can I specify the version in UnityPy to open this kind of bundle? 

EDIT: The `extract_bundle` function in question:

```py
def extract_bundle(file: bytes, dest: str) -> None:
    # Ensure forward slash
    if dest[-1] != '/': dest = dest + '/'
    # load that file via AssetsManager
    env = UnityPy.load(file)
    has_files = False
    # iterate over all assets and named objects
    for obj in env.objects:
        # only process specific object types
        if obj.type.name in ["Texture2D", "Sprite"]:
            # parse the object data
            data = obj.read()
            # Make sure that the extension is PNG so split
            name = os.path.splitext(data.name)[0]
            # Save image
            destfile = dest + name + '.png'
            print("Writing {}".format(destfile))
            data.image.save(destfile)
            has_files = True
        elif obj.type.name == "TextAsset":
            # parse the object data
            data = obj.read()
            # Save data
            destfile = dest + data.name
            print("Writing {}".format(destfile))
            with open(destfile, 'wb') as f: f.write(data.script)
            has_files = True
    if has_files == False:
        raise Exception("No files extracted. Is UnityPy updated?")
```

**Comment by MikuAuahDark** [comment]
Fixed in 05da7ce79e8955a0ec9dee38c1b2772ce268da48.

Example code to set fallback version:

```py
import UnityPy

UnityPy.config.FALLBACK_UNITY_VERSION = "actual unity version"
```
