### ISSUE TITLE
AudioClip class passes a parameter into SerializedFile.read(), which does not accept parameters.

### ISSUE THREAD

**Issue by ievans3024** [K0lb3/UnityPy#11]
Attempting to read AudioClip objects results in a `TypeError` as follows:

```
>>> for asset in am.assets.values():
...     for obj in asset.objects.values():
...         if obj.type.name == 'AudioClip':
...             data = obj.read()
...             print(data)
...             break
... 
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/ian/.local/lib/python3.8/site-packages/UnityPy/files/SerializedFile.py", line 670, in read
    return getattr(classes, self.type.name, classes.Object)(self)
  File "/home/ian/.local/lib/python3.8/site-packages/UnityPy/classes/AudioClip.py", line 57, in __init__
    self.m_AudioData = reader.read(m_Size)
TypeError: read() takes 1 positional argument but 2 were given
```

**Comment by K0lb3** [comment]
I'm sorry,
but I can't replicate your problem.

Please share the asset which causes the error.

**Comment by K0lb3** [comment]
Nvm,
found the problem and fixed it.
[1.4.2 AudioClip fix](https://github.com/K0lb3/UnityPy/commit/74a49da1470bc5e8a5088db950384eb47aefbcf2)

Thanks for reporting the problem.
