### ISSUE TITLE
AttributeError: 'TypeTreeNode' object has no attribute 'type'

### ISSUE THREAD

**Issue by matasis** [K0lb3/UnityPy#117]
**Code**

```python
for obj in env.objects:
    if obj.type.name == "MonoBehaviour":
        MonoData=obj.read()
        sc=MonoData.m_Script.read()
        typetree=getTypeTree(treepath+sc.m_AssemblyName+".json",sc.m_ClassName,sc.m_Namespace)
        res=obj.read_typetree(typetree)
```

**Error**

```
Traceback (most recent call last):
  File "getMono.py", line 31, in <module>
    main()
  File "getMono.py", line 26, in main
    res=obj.read_typetree(typetree)
  File "D:\Anaconda\lib\site-packages\UnityPy\files\ObjectReader.py", line 206, in read_typetree
    tree = TypeTreeHelper.read_typetree(nodes, self)
  File "D:\Anaconda\lib\site-packages\UnityPy\helpers\TypeTreeHelper.py", line 139, in read_typetree
    obj[node.name] = read_value(nodes, reader, i)
  File "D:\Anaconda\lib\site-packages\UnityPy\helpers\TypeTreeHelper.py", line 154, in read_value
    typ = node.type
AttributeError: 'TypeTreeNode' object has no attribute 'type'
```

**Bug**
My Typetree is generated by [K0lb3/TypeTreeGenerator](https://github.com/K0lb3/TypeTreeGenerator), just like this:
```json
"PlayMaker.Actions.ArrayObjects":[
    {
        "m_Type": "MonoBehaviour",
        "m_Name": "Base",
        "m_MetaFlag": 0,
        "m_Level": 0
    },
    {
        "m_Type": "PPtr<GameObject>",
        "m_Name": "m_GameObject",
        "m_MetaFlag": 0,
        "m_Level": 1
    },
    {
        "m_Type": "int",
        "m_Name": "m_FileID",
        "m_MetaFlag": 0,
        "m_Level": 2
    }
]
```
The node I print is
`{'m_Type': 'MonoBehaviour', 'm_Name': 'Base', 'm_MetaFlag': 0, 'm_Level': 0}`
the key is "m_Type" not type.

**To Reproduce**
- Python version=3.9.7
- UnityPy version=1.8.14

**Comment by matasis** [comment]
I use [examples/MonoBehaviourFromAssembly](https://github.com/K0lb3/UnityPy/tree/master/examples) generate typetree can be used.
