### ISSUE TITLE
Unable to load APK files directly

### ISSUE THREAD

**Issue by Elioty** [K0lb3/UnityPy#205]
**Code**
```
PS C:\...> python.exe
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> fd = open(r'C:\...\com.smallgiantgames.empires_60.0.1-1979.apk', mode='rb') 
>>> fd.read(4) 
b'PK\x03\x04'
>>> fd.close() 
>>> import UnityPy 
>>> env = UnityPy.load(r'C:\...\com.smallgiantgames.empires_60.0.1-1979.apk')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\AppData\Roaming\Python\Python310\site-packages\UnityPy\__init__.py", line 8, in load
    return Environment(*args, fs=fs, **kwargs)
  File "C:\...\AppData\Roaming\Python\Python310\site-packages\UnityPy\environment.py", line 40, in __init__
    self.load_zip_file(arg)
  File "C:\...\AppData\Roaming\Python\Python310\site-packages\UnityPy\environment.py", line 147, in load_zip_file
    self.load_assets(z.namelist(), lambda x: z.open(x, "r"))
  File "C:\...\AppData\Roaming\Python\Python310\site-packages\UnityPy\environment.py", line 278, in load_assets
    self.load_file(data, name=path)
  File "C:\...\AppData\Roaming\Python\Python310\site-packages\UnityPy\environment.py", line 127, in load_file
    f = ImportHelper.parse_file(
  File "C:\...\AppData\Roaming\Python\Python310\site-packages\UnityPy\helpers\ImportHelper.py", line 140, in parse_file
    f = files.WebFile(reader, parent, name=name, is_dependency=is_dependency)
TypeError: WebFile.__init__() got an unexpected keyword argument 'is_dependency'
>>> UnityPy.__version__
'1.10.2'
```

**Error**
See the traceback above.

**Bug**
Older versions (1.9.x I think) had no problem to load APK files directly but I always get the above exception on the latest version.
If I unzip the asset bundle myself and give them to UnityPy.load, it works without any issue.
I had a quick look at the massive code base and I saw the check of the signature at the beginning of the file to load and you can see above, the file correctly starts with b'PK\x03\x04' as expected and as what is supposed to be checked against to decide whether the file is an APK file.

**To Reproduce**
- You can find the file used above on any APK mirror website.
- following data:
  - Python version: Python 3.10.4
  - UnityPy version: 1.10.2

**Comment by Elioty** [comment]
I fixed the other issue (#206) locally and made a PR but have not dug into this issue to figure out the root cause of the problem. Just scratch the top and I do not really see where it might come from but you certainly know your code base a lot better to find this out quickly.
