### ISSUE TITLE
Can't load Unity 4.7.2f1 files while AssetStudio does.

### ISSUE THREAD

**Issue by 0x07E5** [K0lb3/UnityPy#237]
**Code**
A snippet of the code section that cases the bug or error.

```
env = UnityPy.load("example.unity3d")
```

**Error**
The error message that is produced by python.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\0x07E5\AppData\Local\Programs\Python\Python310\lib\site-packages\UnityPy\__init__.py", line 8, in load
    return Environment(*args, fs=fs, **kwargs)
  File "C:\Users\0x07E5\AppData\Local\Programs\Python\Python310\lib\site-packages\UnityPy\environment.py", line 46, in __init__
    self.load_file(arg)
  File "C:\Users\0x07E5\AppData\Local\Programs\Python\Python310\lib\site-packages\UnityPy\environment.py", line 137, in load_file
    f = ImportHelper.parse_file(
  File "C:\Users\0x07E5\AppData\Local\Programs\Python\Python310\lib\site-packages\UnityPy\helpers\ImportHelper.py", line 139, in parse_file
    f = files.BundleFile(reader, parent, name=name, is_dependency=is_dependency)
  File "C:\Users\0x07E5\AppData\Local\Programs\Python\Python310\lib\site-packages\UnityPy\files\BundleFile.py", line 40, in __init__
    m_DirectoryInfo, blocksReader = self.read_web_raw(reader)
  File "C:\Users\0x07E5\AppData\Local\Programs\Python\Python310\lib\site-packages\UnityPy\files\BundleFile.py", line 72, in read_web_raw
    uncompressedBytes = CompressionHelper.decompress_lzma(
  File "C:\Users\0x07E5\AppData\Local\Programs\Python\Python310\lib\site-packages\UnityPy\helpers\CompressionHelper.py", line 39, in decompress_lzma
    return dec.decompress(data[5:])
_lzma.LZMAError: Corrupt input data
```

**Bug**
A description of what you expect to happen/see and what actually happens.

Can't load Unity 4.7.2f1 files.

**To Reproduce**
- a copy of the file that causes the problem
[examples.zip](https://github.com/K0lb3/UnityPy/files/15505838/examples.zip)
Inside the package:
  - example-android.unity3d Android sample, AssetStudio can load.
  - example-ios.unity3d iOS sample, AssetStudio can load.
  - example-android-2.unity3d Android sample, AssetStudio can't load as well, idk why. This is not an isolated case, and I have a lot samples. I confirmed they are not encrypted.

- following data:
  - Python version 3.10.1
  - UnityPy version 1.10.13

**Comment by K0lb3** [comment]
UnityPy can load the same files as AssetStudio for the given samples.
Some of the samples can't be loaded by either, which still has to be investigated.

Either these not working samples are corrupted, or the loader still has to be adjusted.
