### ISSUE TITLE
Example of brute_force_key

### ISSUE THREAD

**Issue by ThePiousDragon** [K0lb3/UnityPy#287]
I am trying to load some assets from a Chinese game that UnityPy is telling me is decrypted and I need to use brute_force_key to try to decrypt it. The code that I am trying to use it with is the following (key_sig and data_sig values are provided by UnityPy)

**Code**
import os
import UnityPy

fp = os.path.join(os.path.expanduser("~"), 'global-metadata.dat')

key_sig = b'L\xfa\xe8\xd9\xbb8\x14\xc7\xccU\x977S\xdfz\x94'
data_sig = b'\xa3S[\xcdo\x98I8\xa1\x9a\xdf\xc2\xbc|\x92\xb1',

result = UnityPy.helpers.ArchiveStorageManager.brute_force_key(fp, key_sig, data_sig)

print(result)

**Error**
The error I get is 

```
Traceback (most recent call last):
  File "/Users/----/Downloads/parser/unity.py", line 9, in <module>
    result = UnityPy.helpers.ArchiveStorageManager.brute_force_key(fp, key_sig, data_sig)
  File "/Users/----/Downloads/parser/lib/python3.10/site-packages/UnityPy/helpers/ArchiveStorageManager.py", line 56, in brute_force_key
    signature = decrypt_key(key_sig, data_sig, key)
  File "/Users/----/Downloads/parser/lib/python3.10/site-packages/UnityPy/helpers/ArchiveStorageManager.py", line 39, in decrypt_key
    return bytes(x ^ y for x, y in zip(data, key))
  File "/Users/----/Downloads/parser/lib/python3.10/site-packages/UnityPy/helpers/ArchiveStorageManager.py", line 39, in <genexpr>
    return bytes(x ^ y for x, y in zip(data, key))
TypeError: unsupported operand type(s) for ^: 'bytes' and 'int'
```

**Bug**
I am not sure if it's a bug or I am using the functionality incorrectly :/ 

**To Reproduce**
- a copy of the file that causes the problem: here is global-metadata.dat https://files.catbox.moe/bff9hk.dat
- following data:
  - Python version: 3.10
  - UnityPy version: 1.20.16

```
LookupError: The BundleFile is encrypted, but no key was provided!
You can set the key via UnityPy.set_assetbundle_decrypt_key(key).
To try brute-forcing the key, use UnityPy.helpers.ArchiveStorageManager.brute_force_key(fp, key_sig, data_sig)
with  key_sig = b'L\xfa\xe8\xd9\xbb8\x14\xc7\xccU\x977S\xdfz\x94', data_sig = b'\xa3S[\xcdo\x98I8\xa1\x9a\xdf\xc2\xbc|\x92\xb1',and fp being the path to global-metadata.dat or a memory dump.
```

**Comment by ThePiousDragon** [comment]
I am dumb, it was the training comma after `data_sig = b'\xa3S[\xcdo\x98I8\xa1\x9a\xdf\xc2\xbc|\x92\xb1',` :/ 
But I still couldn't find the key with those parameters, either with global-metadata.dat or a memory dump. Is there something else I could try?

**Comment by K0lb3** [comment]
The key can also be generated at runtime or be stored somewhere else.
The brute-force approach for the given files basically only works if the game developers don't have a clue about encryption and simply use the ready made solution by Unity CN Pro with a static hard coded key.....and there are quite a lot of devs like this.....

**Comment by K0lb3** [comment]
You can try to use frida or other tools to see if you can simply dump the key from memory by hooking the ``SetAssetBundleKey`` function.

**Comment by ThePiousDragon** [comment]
Thanks for the reply. I tried using Frida do dump `SetAssetBundleKey` but it didn't work. It probably calls it at runtime because when I try to spawn the process with Frida directly it terminates it immediately. I have to launch the process manually and then attach Frida to it, and after that it doesn't seem to be calling `SetAssetBundleKey`. 
It seems like they've gone through some trouble to protect their encryption :/ If there is anything else I can check for that's simple enough I can try, but other than that probably not worth the trouble so we can close this. Thank you for trying to help.
