### ISSUE TITLE
How to import/export monobehaviors from asset files?

### ISSUE THREAD

**Issue by CloudSodaZero** [K0lb3/UnityPy#289]
**Game**
Muck
(Steam free game. [Muck](https://store.steampowered.com/app/1625450/Muck/))

*Files I used*
- Windows 10 x64
- Python 3.12.6
- UnityPy Version: 1.20.16
- Typetree Json file(Extracted using [this module](https://github.com/jrobinson3k1/typetree_unity): [typetree.json](https://github.com/user-attachments/files/18270244/typetree.json)

**Code**
Code 1
```import json
import UnityPy

env = UnityPy.load("level0")
for obj in env.objects:
    if obj.type.name == "MonoBehaviour":
        if obj.serialized_type.node:
            print(obj.read_typetree())
```
  
Code 2
```
import json
import UnityPy

with open("typetree.json", "r") as f:
    typetree_data = json.load(f)

env = UnityPy.load("level0")
for obj in env.objects:
    if obj.type.name == "MonoBehaviour":
        monobehaviour = obj.read()
        script = monobehaviour.m_Script.read()
        if obj.serialized_type.nodes:
            tree = obj.read_typetree()

        else:
            if script.m_Namespace == "":
                typetree = typetree_data[script.m_AssemblyName][script.m_ClassName]
            else:
                typetree = typetree_data[script.m_AssemblyName][
                    f"{script.m_Namespace}.{script.m_ClassName}"
                ]
            tree = obj.read_typetree(typetree)
        print(tree)
```

**Error**
Code 1 is the one I used in the past to extract Monobehaviour from a .bundle file with a built-in typetree.
If you run the code above, it won't produce any output, probably because it doesn't have a typetree built in.

Code 2 results in an error as shown below.
```
Traceback (most recent call last):
  File "c:\Program Files (x86)\Steam\steamapps\common\Muck\Muck_Data\main.py", line 10, in <module>
    monobehaviour = obj.read()
                    ^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python312\site-packages\UnityPy\files\ObjectReader.py", line 174, in read
    obj = self.read_typetree(wrap=True, check_read=check_read)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python312\site-packages\UnityPy\files\ObjectReader.py", line 210, in read_typetree
    ret = TypeTreeHelper.read_typetree(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python312\site-packages\UnityPy\helpers\TypeTreeHelper.py", line 149, in read_typetree
    raise ValueError(
ValueError: Expected to read 52 bytes, but only read 32 bytes
```

if I edit obj.read() to obj.read(check_read=False), The error message will be different, as shown below.
```
Traceback (most recent call last):
  File "c:\Program Files (x86)\Steam\steamapps\common\Muck\Muck_Data\main.py", line 11, in <module>
    script = monobehaviour.m_Script.read()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python312\site-packages\UnityPy\classes\PPtr.py", line 37, in read
    return self.deref_parse_as_object()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python312\site-packages\UnityPy\classes\PPtr.py", line 92, in deref_parse_as_object
    return self.deref(assetsfile).parse_as_object()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python312\site-packages\UnityPy\classes\PPtr.py", line 81, in deref
    cab = env.find_file(external_clean_path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python312\site-packages\UnityPy\environment.py", line 320, in find_file
    raise FileNotFoundError(f"File {name} not found in {self.path}")
FileNotFoundError: File unity_builtin_extra not found in C:\Program Files (x86)\Steam\steamapps\common\Muck\Muck_Data
```
If I move the unity_builtin_extra file to the Muck_Data folder, I get the same error message.

**Bug**
`It shows ValueError: Expected to read 52 bytes, but only read 32 bytes`
`FileNotFoundError: File unity_builtin_extra not found in C:\Program Files (x86)\Steam\steamapps\common\Muck\Muck_Data`
**To Reproduce**
- [typetree.json](https://github.com/user-attachments/files/18270311/typetree.json)
- [Muck](https://store.steampowered.com/app/1625450/Muck/)
- following data:
  - Python version: 3.12.6
  - UnityPy version: 1.20.16
 
My goal is to modify and import the TextMeshProUGUI asset from the assets in level0.
Can you tell how to extract the Typetree correctly, how to load it and how to extract the Monobehaviour from the .asset file using the Typetree json?
Thank you for your hard work.

**Comment by t-wy** [comment]
There seems to be a `check_read` parameter added following Commit 2f79790.

Probably need to set `check_read=False` for `.read()` and `.read_typetree()` to get the original behavior.

**Comment by stypr** [comment]
This happens to be a same error I've been getting. I think there is a bug with the struct aligning but I don't knwo what is the correct issue.

For me, `monobehaviour.deref().get_raw_data().tobytes()` did work but I have some issues aligning those from the memory directly.

**Comment by stypr** [comment]
Ok, I did some research and noticed what was the problem.

Try this out if it works on your machine. 
I haven't run your code, but apparently `obj.read()` on MonoBehaviour requires `check_read=False` as the parameter. I assume it should work.

```py
import json
import UnityPy

with open("typetree.json", "r") as f:
    typetree_data = json.load(f)

env = UnityPy.load("level0")
for obj in env.objects:
    if obj.type.name == "MonoBehaviour":
        monobehaviour = obj.read(check_read=False)
        script = monobehaviour.m_Script.read()
        if obj.serialized_type.nodes:
            tree = obj.read_typetree()

        else:
            if script.m_Namespace == "":
                typetree = typetree_data[script.m_AssemblyName][script.m_ClassName]
            else:
                typetree = typetree_data[script.m_AssemblyName][
                    f"{script.m_Namespace}.{script.m_ClassName}"
                ]
            tree = obj.read_typetree(typetree)
        print(tree)
```

This is a bit off-topic from this issue, but I encountered some bug where raw_data is not being parsed correctly when compared with the older version's raw_data. 

It turns out that `get_raw_data()` now prints out  both metadata and actual data on the newer version, causing memory misalignment while you fetch the raw data. 

For example on this issue's output, the error `Expected to read 52 bytes, but only read 32 bytes` seems pretty related as you need to fetch raw data starting from that 32nd byte.

If you plan to migrate from older version to newer version of UnityPy, note that the real raw data you used to get from the old version will start from `target_object.deref().byte_start / 4`. 

```py
            target_object_start = int(target_object.deref().byte_start / 4)
            target_object_raw = target_object.deref().get_raw_data().tobytes()
            target_object_raw_real = target_object_raw[target_object_start:]

```
