### ISSUE TITLE
AttributeError: module 'PIL._imaging' has no attribute 'etc2_decoder'

### ISSUE THREAD

**Issue by minhducsun2002** [K0lb3/UnityPy#8]
```
Traceback (most recent call last):
  File "<censored>/UnityPy/lib/python3.8/site-packages/PIL/Image.py", line 409, in _getdecoder
    decoder = getattr(core, decoder_name + "_decoder")
AttributeError: module 'PIL._imaging' has no attribute 'etc2_decoder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<censored>/UnityPy/AssetBatchConverter.py", line 116, in <module>
    main()
  File "<censored>/UnityPy/AssetBatchConverter.py", line 42, in main
    extract_assets(src)
  File "<censored>/UnityPy/AssetBatchConverter.py", line 63, in extract_assets
    export_obj(obj, fp)
  File "<censored>/UnityPy/AssetBatchConverter.py", line 97, in export_obj
    data.image.save(f"{fp}{extension}")
  File "<censored>/UnityPy/UnityPy/classes/Sprite.py", line 13, in image
    return SpriteHelper.get_image_from_sprite(self)
  File "<censored>/UnityPy/UnityPy/export/SpriteHelper.py", line 45, in get_image_from_sprite
    original_image = get_image(m_Sprite, m_Texture2D, alpha_texture)
  File "<censored>/UnityPy/UnityPy/export/SpriteHelper.py", line 28, in get_image
    original_image = get_image_from_texture2d(texture.read(), False)
  File "<censored>/UnityPy/UnityPy/export/Texture2DConverter.py", line 258, in get_image_from_texture2d
    img = Image.frombytes(mode, (texture_2d.m_Width, texture_2d.m_Height), image_data, codec, args)
  File "<censored>/UnityPy/lib/python3.8/site-packages/PIL/Image.py", line 2581, in frombytes
    im.frombytes(data, decoder_name, args)
  File "<censored>/UnityPy/lib/python3.8/site-packages/PIL/Image.py", line 767, in frombytes
    d = _getdecoder(self.mode, decoder_name, args)
  File "<censored>/UnityPy/lib/python3.8/site-packages/PIL/Image.py", line 412, in _getdecoder
    raise OSError("decoder %s not available" % decoder_name)
```

I can as well provide the assets file if you wish.

**Comment by K0lb3** [comment]
Even tho I already answered on discord - this issue has to be closed with an answer as well.

The cause of this problem is that the module [etcpack](https://github.com/K0lb3/etcpack) wasn't installed. There should have been a message made by UnityPy in the command prompt about it as well.
This module was necessary for the [old version](https://github.com/K0lb3/UnityPy/blob/4f8073391514528498ed209265f3dec739bc6d27/UnityPy/export/Texture2DConverter.py) you're using to decompress etc.

So, to resolve your problem you can either upgrade UnityPy or install the missing module.
